name: Default Action
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Compile LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@1.0.5
        with:
          root_file: main.tex
          extra_packages: "acronym anyfontsize babel booktabs csvsimple enotez fontenc geometry glossaries graphicx hyperref hyphenat imakeidx inputenc lettrine lmodern longtable microtype multicol pdfpages tikzpagenodes titlesec xcolor"
